// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YC5.Data;

#nullable disable

namespace YC5.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260210182226_InitialSeedData")]
    partial class InitialSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YC5.Models.Function", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Functions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "STUDENT_VIEW",
                            Name = "Xem danh sách sinh viên"
                        },
                        new
                        {
                            Id = 2,
                            Code = "STUDENT_CREATE",
                            Name = "Thêm mới sinh viên"
                        },
                        new
                        {
                            Id = 3,
                            Code = "STUDENT_UPDATE",
                            Name = "Cập nhật sinh viên"
                        },
                        new
                        {
                            Id = 4,
                            Code = "STUDENT_DELETE",
                            Name = "Xóa sinh viên"
                        },
                        new
                        {
                            Id = 5,
                            Code = "STUDENT_IMPORT",
                            Name = "Import sinh viên"
                        },
                        new
                        {
                            Id = 6,
                            Code = "STUDENT_EXPORT",
                            Name = "Export sinh viên"
                        });
                });

            modelBuilder.Entity("YC5.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("YC5.Models.RoleFunction", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("FunctionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "FunctionId");

                    b.ToTable("RoleFunctions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            FunctionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            FunctionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            FunctionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            FunctionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            FunctionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            FunctionId = 6
                        });
                });

            modelBuilder.Entity("YC5.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MSSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MSSV")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Class = "D15-01",
                            DateOfBirth = new DateTime(2002, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "an.nv@gmail.com",
                            FullName = "Nguyễn Văn An",
                            MSSV = "SV001",
                            Major = "CNTT",
                            Phone = "0912345678"
                        },
                        new
                        {
                            Id = 2,
                            Class = "K15-02",
                            DateOfBirth = new DateTime(2002, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "binh.tt@gmail.com",
                            FullName = "Trần Thị Bình",
                            MSSV = "SV002",
                            Major = "Kế toán",
                            Phone = "0988776655"
                        });
                });

            modelBuilder.Entity("YC5.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("YC5.Models.UserFunction", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("FunctionId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "FunctionId");

                    b.ToTable("UserFunctions");
                });

            modelBuilder.Entity("YC5.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
